#!/usr/bin/env bash
# Your Bash script must accept 2 arguments

dig_function ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	dig_function "$1" "$subdomain"
    fi
done
