#!/usr/bin/env bash
#Is a bash script that install nginx

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx restart
