#!/usr/bin/env bash
# Is a bash escript that configures Nginx server witha  custome HTTP header

sudo apt-get update
sudo apt-get -y install nginx
header="\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "31i\ $header" /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
