#!/usr/bin/env bash
# Is a Bash script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get -y install haproxy
echo 'ENABLED=1' >> /etc/default/haproxy
cat >> /etc/haproxy/haproxy.cfg << CONFIG
frontend front
    bind :80
    default_backend back
backend back
    balance roundrobin
    server 2753-web-01 34.74.201.211:80
    server 2753-web-02 34.138.193.238:80
CONFIG
sudo service haproxy restart
