#!/usr/bin/env bash
# Is a Bash script that transfers a file from our client to a server:
if [ $# -eq 2 ]
then
	scp -i "~/.ssh/holberton" -o StrictHostKeyChecking=no "$1" "ubuntu@$2":
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP"
fi
