#!/usr/bin/env bash
# Is a Bash script that configures a server to the above requirements
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
