#!/usr/bin/env bash
# Is a Bash script that displays Holberton School 10 times,
# but for the 9th iteration, displays Holberton School and then
# Hi on a new line.

i=1
while [ $i -le 10 ]
do
	echo Holberton School
	if [ $i == 9 ]
	then
		echo Hi
	fi
	((i++))
done
