#!/usr/bin/env bash
# Is a Bash script that gives you information about the
# holbertonschool file.

file_name=holbertonschool
if [ -e $file_name ]
then
    echo "$file_name file exists"
    if [ -s $file_name ]
    then
	echo "$file_name file is not empty"
    else
	echo "$file_name file is empty"
    fi
    if [ -f $file_name ]
	then
	    echo "$file_name is a regular file"
    fi
else
    echo "$file_name file does not exist"
fi
