#!/usr/bin/env bash
# Is a Bash script that configures
# an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo 8.8.8.8		facebook.com >> /etc/hosts
